### ISSUE TITLE
SuperSync still has problem "screen tearing"[Do not know WHY]

### ISSUE THREAD

**Issue by kissingfire123** [Consti10/FPV_VR_OS#10]
Hi Consti10:
      I'd like to practice lowest latency VR with "Strip-Render" (or "Beam Racing") . I think your code is completely reasonalble. 
But unluckly, I switch VR-Setting to **SuperSync** , and adjust my Xiaomi12 to **120Hz** screen refresh rate , then **I see sawtooth flasing**.

Ps: I use Android Studio to debug the program, and found out `VSYNC.h` print warning info --> "`Got VSYNC in the future`".

**Comment by kissingfire123** [comment]
attach a picture which shows the problem call from FBRManager::warpEyesToFrontBufferSynchronized
![FPV-VR-stack-Call](https://user-images.githubusercontent.com/23032593/176086987-c791dc5e-679a-4dbe-ab3d-bcae7934f0c8.png)

**Comment by kissingfire123** [comment]
![image](https://user-images.githubusercontent.com/23032593/176090465-d551d1e0-d3cf-4133-949a-fc558a36537b.png)

**Comment by Consti10** [comment]
Hello,

The problem here is most likely that at the time FPV_VR was written, there was no 120hz support on android yet.

And even as of now, there is no way (to my knowledge) of reading the vsync timing info exact enough from the android system for 120hz (assuming a really powerfull GPU).

If you want to thinker with it, you already found the parts of the code that would need to be modified for 120hz - but I don't have any plans to work on that, since you can always use "Disable VSYNC" and live with the almost unnoticable tearing.

One more thing:
Instead of 8.3ms (half a frame 60hz) the GPU must be capable of warping the scene for one eye at 4.15 ms - I am not sure if that is even possible on the highest performance flagship phones.

**Comment by Consti10** [comment]
Regarding VSYNC timing - in theory, the task is simple (we need to know when the VSYNC starts and how long it takes) - unfortunatlely, android does not make this information easily accessible, so VSYNC.h was always a bit of a hack.

**Comment by kissingfire123** [comment]
@Consti10  Thanks so much for repling. I found the key reson is "Can't  render(offscreen+onScreen) an eye within half  sreen-refresh".I decided to create a framebuffer queue to store screen result ,and render within 2  refresh frames. Wish it works
